config/routes.rb
Earlymorningpost::Application.routes.draw do
  root :to => 'pages#home'

  resources :news do
    put :like
  end

  resources :categories
  resources :sessions, only: [:new, :create, :destroy]

  match "/admin",          :to => "sessions#new", :via => :get
  match "/byebye",         :to => "sessions#destroy", :via => :get

  match "/about",          :to => "pages#about", :via => :get
  match "/contact",        :to => "pages#contact", :via => :get

  match "sitemap",         :to => "sitemap#sitemap", :via => :get
  match "rssfeed",         :to => 'sitemap#rssfeed',   :via => :get
  match "BingSiteAuth",    :to => "sitemap#BingSiteAuth", :via => :get

end

app/models/news.rb
class News < ActiveRecord::Base
	attr_accessible :title, 
					:content, 
					:category_id, 
					:sub_heading,
					:author,
					:image_courtesy, 
					:image,
					:remote_image_url,
					:video_url

	paginates_per 50

	belongs_to :category

	# Validations, a news should have a Content, Title and Category ID.
	validates :content, presence: true
	validates :title, presence: true
	validates :category_id, presence: true

	# to associate carrierwave images to the model
	mount_uploader :image, ImageUploader

	# This sets the order of the news from New to Old, 
	# based on when it was updated.
	default_scope -> { order('updated_at DESC') }

  after_destroy :delete_image_from_s3

  def self.parse_and_create_news(feed_url, category)
    doc = Nokogiri::XML open(feed_url)

    doc.css("item").each do |item|
      google_link = item.xpath("link").text
      google_link =~ /url=(.*)/
      link = $1

      item.xpath("guid").text =~ /cluster=(\d{1,45})/
      guid = $1
      existing_news = News.find_by_source_id(guid)

      if existing_news
        Rails.logger.info "##### News with #{guid} already published #####"
        existing_news.save
        next
      end

      read_and_create(link, category, source_id: guid)
    end
  end

  def self.read_and_create(link, category, options = {})
    source_id = options.delete(:source_id)
    source = open(link).read rescue nil
    return unless source

    parsed = Readability::Document.new(source)
    news = News.new
    news.title = parsed.title.strip.gsub("\n", "")
    news.content = parsed.content
    news.remote_image_url = parsed.images.first unless parsed.images.empty?
    news.link = link
    news.source_id = source_id
    news.source_name = parse_source(news.title)
    news.category = category
    news.external = true

    if news.save
      Rails.logger.info "###### OK ########"
    else
      Rails.logger.warn "##### ERRORS ######"
      Rails.logger.warn news.errors.full_messages
    end
  end

	def to_param
		"#{id}+#{title.parameterize}"
	end

  def self.parse_source(text)
    # Scanning the last 25% of the string
    percent = text.length - (0.25 * text.length).round
    text = text[percent..-1]

    if text.include?(" | ")
      text =~ /\|(.*)/
      return $1.strip || nil
    elsif text.include?(" : ")
      text =~ /\:(.*)/
    elsif text.include?(" - ")
      text =~ /\-(.*)/
    end

    return $1.strip if $1
  end

  def delete_image_from_s3
    self.remove_image!
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	# Find the methods in the Application Controller
	before_filter :authenticate, except: [:show, :like]

	def index
		@news = News.order(:created_at).page params[:page]
		@title = "Index"
	end
	
	def new
		@news = News.new
		@category = Category.all
		@title = "Add News"
	end

	def create
    category = Category.find params[:news][:category_id]

    if !params[:source_link].blank?
      News.read_and_create(params[:source_link], category)

      redirect_to category_path(Category.find(category))
      return
    elsif !params[:feed_url].blank?
      News.parse_and_create_news(params[:feed_url], category)

      redirect_to category_path(Category.find(category))
    else
      @news = News.new(params[:news])
      if @news.save
        redirect_to @news, :flash => { :notice => "News Posted!"}
      else
        render 'new'
      end
    end 
	end

	def show
		@news = News.find(params[:id])
		@title = @news.title
	end

	def edit
		@news = News.find(params[:id])
		@title = "Edit"	
	end

	def update
		@news = News.find(params[:id])
		if @news.update_attributes(params[:news])
			redirect_to @news, :flash => { :notice => "News Updated!" }
		else
			@title = "Edit"
			render 'edit'
		end
	end

	def destroy
		@news = News.find(params[:id])
		@news.destroy

    flash[:alert] = "News Deleted"
    redirect_to news_index_path
	end

  def like
    @news = News.find(params[:news_id])

    if @news.like!
      respond_to do |format|
        format.json { render json: @news.likes, status: :no_content }
      end
    else
      respond_to do |format|
        format.json { render json: "ERROR", status: :bad_request }
      end
    end
  end

	private

  def news_params
    params.require(:news).permit(:title, :content, :category)
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_news_fields.html.haml
.field
  = f.label :title
  = f.text_field :title, :class => 'add-title'
.field
  = f.label :sub_heading
  = f.text_area :sub_heading, :class => 'add-sub-heading'
.field
  = f.label :content
  = f.text_area :content, :size => "30x20", :class => 'add-content'
.field
  = f.file_field :image
.field
  = f.label :remote_image_url, "or Image URL"
  = f.text_field :remote_image_url
.field
  = f.label :image_courtesy
  = f.text_field :image_courtesy
.field
  = f.label :author
  = f.text_field :author
.field
  = f.label 'YouTube Video ID'
  = f.text_field :video_url
.field
  = f.label 'active'
  = f.check_box :active
%hr
.field
  = f.label "Google News URL"
  = text_field_tag :feed_url
%hr
.field
  = f.label "Source URL"
  = text_field_tag :source_link
.field
  = collection_select :news, :category_id, Category.all, :id, :name, |
    { :prompt => 'Please select a cateogry' }, :class => 'dropdown'  |

app/views/news/_news_index.html.haml
%span.index-title
  = link_to news.title, news
%span.index-description
  %span.index-date
    = news.category.name
    |
    \#{news.created_at.strftime("%d %b %y")}
  = link_to 'Edit', edit_news_path(news), :class => 'button tiny radius'
  = link_to 'Delete', news_path(news), method: :delete, confirm: "Are you sure?", title: "Delete #{news.title}", class: 'button tiny alert radius'

app/views/news/edit.html.haml
%h1 Edit News
= form_for(@news) do |f|
  = render 'shared/error_messages'
  = render 'news_fields', :f => f
  .actions
    = f.submit "Update", :class => 'button'

app/views/news/index.html.haml
.row
  .large-6.columns
    %h1.index All News
  .large-6.columns
    = link_to "New News", new_news_path, :class => "buttons button round"
%hr/
.row
  .large-12.columns
    %ul.news-list
      - for news in @news
        %li
          = render 'news_index', :news => news
    = paginate @news

app/views/news/new.html.haml
%h1 Add News
= form_for(@news) do |f|
  = render 'shared/error_messages'
  .fields
    = render 'news_fields', f: f
  .actions
    = f.submit "Save", :class => 'button'

app/views/news/show.html.haml
- content_for :head do
  / Normal Tags
  %meta{:content => "#{@news.title}", :name => "title"}/
  %meta{:content => "#{@news.content[0..155]}", :name => "description"}/
  %meta{:content => "#{%W[#{@news.category.name} News]}", :name => "keywords"}/
  / Schema.org markup for Google+
  %meta{:content => "#{@news.title}", :itemprop => "name"}/
  %meta{:content => "#{@news.content[0..155]}", :itemprop => "description"}/
  %meta{:content => "#{@news.image_url}", :itemprop => "image"}/
  / Open Graph Meta Tags
  %meta{:content => "#{@news.title}", :property => "og:title"}/
  %meta{:content => "website", :property => "og:type"}/
  %meta{:content => "#{@news.image_url}", :property => "og:image"}/
  %meta{:content => "#{request.url}", :property => "og:url"}/
  %meta{:content => "#{@news.content[0..155]}", :property => "og:description"}/
  %meta{:content => "Early Morning Post", :property => "og:site_name"}/
  %meta{:content => "#{@news.category.name}", :property => "article:section"}/
  %meta{:content => "#{%W[#{@news.category.name} News]}", :property => "article:tag"}/
  / Twitter Meta Tags
  %meta{:content => "summary_large_image", :name => "twitter:card"}/
  %meta{:content => "#{@news.title}", :name => "twitter:title"}/
  %meta{:content => "#{@news.content[0..155]}", :name => "twitter:description"}/
  / Twitter summary card with large image must be at least 280x150px
  %meta{:content => "@news.image_url", :name => "twitter:image:src"}/
%div{:itemscope => "", :itemtype => "http://schema.org/Article"}
  %h1{:itemprop => "name"}= @news.title
  %h4= @news.sub_heading
  .news-date
    - if @news.created_at > 2.days.ago
      = time_ago_in_words(@news.created_at).upcase
      AGO
    - else
      = @news.created_at.to_formatted_s(:long_ordinal)
      UTC
    - if @news.author?
      |
      %strong
        BY #{@news.author.upcase}
  - if admin?
    .admin-buttons
      = link_to 'Edit', edit_news_path(@news), :class => 'button tiny radius'
      = link_to 'Delete', @news, :method => :delete, |
        :confirm => "Are you sure?",                 |
        :title => "Delete #{@news.title}",           |
        :class => 'button tiny alert radius'         |
  .news-image
    %span{:itemprop => "image"}= image_tag @news.image_url if @news.image?
  - if @news.image_courtesy?
    .image-courtesy
      Image Courtesy #{@news.image_courtesy}
  .social-likes.social-likes_light
    .facebook{:title => "Share this on Facebook"} Facebook
    .twitter{:title => "Tweet it!"} Twitter
    .plusone{:title => "Share this on Google+"} Google+
    .pinterest{"data-media" => "", :title => "Share image on Pinterest"} Pinterest
  %hr/
  #news-content
    %span{:itemprop => "description"}= simple_format @news.content
  - if @news.video_url?
    .embedded-video
      %iframe#iFrame{:frameborder => "0", :height => "640px", :src => "//www.youtube.com/embed/#{@news.video_url}?wmode=opaque", :width => "100%"}
  #comments
    %hr/
    %h3.comments-title DISCUSSION
    #disqus_thread
    = javascript_include_tag 'disqus'
    %noscript
      Please enable JavaScript to view the
      %a{:href => "http://disqus.com/?ref_noscript"} comments powered by Disqus.
    %a.dsq-brlink{:href => "http://disqus.com"}
      comments powered by
      %span.logo-disqus Disqus