config/routes.rb
Earlymorningpost::Application.routes.draw do
  root :to => 'pages#home'

  resources :news do
    put :like
  end

  resources :categories
  resources :sessions, only: [:new, :create, :destroy]

  match "/admin",          :to => "sessions#new", :via => :get
  match "/byebye",         :to => "sessions#destroy", :via => :get

  match "/about",          :to => "pages#about", :via => :get
  match "/contact",        :to => "pages#contact", :via => :get

  match "sitemap",         :to => "sitemap#sitemap", :via => :get
  match "rssfeed",         :to => 'sitemap#rssfeed',   :via => :get
  match "BingSiteAuth",    :to => "sitemap#BingSiteAuth", :via => :get

end

app/views/pages/_ad_card.html.haml
.card{ align: 'center' }
  .label-container{ align: 'left' }
    %span.ad-label Ad
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- Header-Medium -->
  <ins class="adsbygoogle" style="display:inline-block;width:300px;height:250px" data-ad-client="ca-pub-8853705788192995" data-ad-slot="6214449267"></ins>
  <script>
  (adsbygoogle = window.adsbygoogle || []).push({});
  </script>

app/views/pages/_card.html.haml
.card{ id: news.to_param }
  - if news.image?
    .image
      - if news.external?
        %a{href: news.link, target: "_blank"}
          = image_tag news.image_url
      - else
        %a{href: "#{news_path(news)}"}
          = image_tag news.image_url
  .card-summary
    #card-captions
      %span.card-category
        = link_to news.category.name.upcase, category_path(news.category)
        |
      %span.card-date
        - if news.created_at > 2.days.ago
          = time_ago_in_words(news.created_at)
          ago
        - else
          = news.created_at.strftime("#{news.created_at.day.ordinalize} %B %y")
    #card-title
      %h1{:itemprop => "name"}
        - if news.external?
          %a{ href: news.link, target: "_blank" }
            #{news.title}
        - else
          = link_to news.title, news, itemprop: "#{request.url}#{news_path(news)}"
    #card-content
      %span{itemprop: "description"}
        - if news.external?
          = "#{strip_tags(news.content.squish)[0..400]} ..."
          .read-more-container
            %a{ href: news.link, target: "_blank" }
              %br
              - if news.source_name
                %span.text-muted more at
                %span.source-name= news.source_name
              - else
                %span.read-more read more &#8594;
            %span.like-news
              = fa_icon "thumbs-o-up",
                class: "like-button",
                id: "like-#{news.id}",
                data: { "news-id": news.id }
              - if news.likes > 0
                %span.like-count{ id: "like-count-#{news.id}"} #{news.likes}
        - else
          = simple_format "#{news.content[0..250]} ..."
          %a{ href: news_path(news) }
            %br/
            %span.text-muted read more &#8594;

app/views/pages/about.html.haml
.center{:align => "center"}
  #page-title
    %h2 &lt;Hello World!/&gt;
  %hr/
  #about-description
    %p
      I am not a blogger, just a web developer, so you might not find great content around here, yet!
      But the idea is to create a Simple and Beautiful looking News website that publishes relevent and trending content related to select topics to the news feed at the home page, and gives the user a clean and beautiful reading experience.
  .medium
    %script{:async => "", :src => "https://static.medium.com/embed.js"}
    %a.m-profile{:href => "https://medium.com/@pranav7"} Pranav Singh

app/views/pages/contact.html.haml
%h1 Contact Us
%p Find me in app/views/pages/contact.html.erb

app/views/pages/entertainment.html.haml
.main
  #page-title
    %h2= @title.upcase
  %hr/
  - if @news.empty?
    %h2 Jim's dead.
  - else
    #cards-wrapper
      - for news in @news
        = render 'card', :news => news

app/views/pages/home.html.haml
.slideshow-wrapper.hide
  .preloader
  %ul.example-orbit{ "data-orbit": true }
    - @news.last(5).each do |news|
      - if news.image?
        %li
          .image-container
            = image_tag news.image_url
          .orbit-caption
            .title= link_to news.title, news
            .category= news.category.name
#cards-wrapper
  - @news.each_with_index do |news, index|
    - if index != 0 && index % 4 == 0
      = render '/pages/ad_card'

    = render '/pages/card', news: news

= paginate @news

app/views/pages/science.html.haml
.main
  #page-title
    %h2= @title.upcase
  %hr/
  - if @news.empty?
    %h2 Jim's dead.
  - else
    #cards-wrapper
      - for news in @news
        = render 'card', :news => news

app/views/pages/sports.html.erb
<div class="main">
	<div id="page-title">
		<h2><%= @title.upcase %></h2>
	</div>
	<hr>

<% if @news.empty? %>
	<h2>Jim's dead.</h2>
<% else %>
	<div id="cards-wrapper">
		<% for news in @news %>
			<%= render 'card', :news => news %>
		<% end %>
	</div>
<% end %>
</div>

app/views/pages/technology.html.haml
.main
  #page-title
    %h2= @title.upcase
  %hr/
  - if @news.empty?
    %h2 Jim's dead.
  - else
    #cards-wrapper
      - for news in @news
        = render 'card', :news => news

app/views/pages/world.html.haml
.main
  #page-title
    %h2= @title.upcase
  %hr/
  - if @news.empty?
    %h2 Jim's dead.
  - else
    #cards-wrapper
      - for news in @news
        = render 'card', :news => news