config/routes.rb
Earlymorningpost::Application.routes.draw do
  root :to => 'pages#home'

  resources :news do
    put :like
  end

  resources :categories
  resources :sessions, only: [:new, :create, :destroy]

  match "/admin",          :to => "sessions#new", :via => :get
  match "/byebye",         :to => "sessions#destroy", :via => :get

  match "/about",          :to => "pages#about", :via => :get
  match "/contact",        :to => "pages#contact", :via => :get

  match "sitemap",         :to => "sitemap#sitemap", :via => :get
  match "rssfeed",         :to => 'sitemap#rssfeed',   :via => :get
  match "BingSiteAuth",    :to => "sitemap#BingSiteAuth", :via => :get

end

app/views/layouts/_facebook.html.haml
%a{:href => "https://www.facebook.com/earlymorningpost", :rel => "publisher", :style => "text-decoration:none;display:inline-block;color:#333;text-align:center; font:13px/16px arial,sans-serif;white-space:nowrap;", :target => "_blank"}
  = image_tag 'facebook.png', size: "31x31", alt: "Facebook"

app/views/layouts/_flash_messages.html.haml
- if flash[:error]
  .flash.error= flash[:error]
- if flash[:success]
  .flash.success= flash[:success]
- if flash[:notice]
  .flash.notice= flash[:notice]
- if flash[:alert]
  .flash.alert= flash[:alert]

app/views/layouts/_footer.html.haml
.footer-top-border
.footer-top
  .row
    #footer-nav.large-3.columns
      %ul
        - Category.all.each do |category|
          %li= fa_icon "#{category.icon}", text: category.name.upcase
    #footer-nav.large-3.column
      %ul
        %li
          %i.fi-social-facebook.size-48
          = link_to "Facebook", "https://www.facebook.com/earlymorningpost"
        %li
          %i.fi-social-google-plus
          = link_to "Google+", "//plus.google.com/u/0/114178803974973491087?prsrc=3"
        %li
          %i.fi-star
          = link_to "About Us", about_path
    .footer-logo.large-6.columns
      = link_to logoFooter
.footer-bottom
  .row
    .large-12.columns
      %p Copyright © Early Morning Post. All Rights Reserved.

app/views/layouts/_google_plus_badge.html.haml
/ Place this code where you want the badge to render.
%a{:href => "//plus.google.com/u/0/114178803974973491087?prsrc=3", :rel => "publisher", :style => "text-decoration:none;display:inline-block;color:#333;text-align:center; font:13px/16px arial,sans-serif;white-space:nowrap;", :target => "_blank"}
  %img{:alt => "Google+", :src => "//ssl.gstatic.com/images/icons/gplus-32.png", :style => "border:0;width:32px;height:32px;"}/

app/views/layouts/_header.html.haml
.header-wrapper.fixed.contain-to-grid
  .top-bar{ data: { topbar: true }, role: "navigation" }
    %ul.title-area
      %li.logo.name.show-for-medium-up
        = link_to logoHeader, root_path
      %li.short-logo.name.show-for-small-only
        = link_to shortLogoHeader, root_path
      %li.toggle-topbar.menu-icon
        %a{href: '#'}
          %span Categories
    .top-bar-section
      %ul.right
        - Category.all.each do |category|
          %li
            %a{href: category_path(category)}
              = fa_icon "#{category.icon}", text: category.name.upcase
        - if admin?
          %li= link_to "News", news_index_path
          %li.divider
          %li= link_to "Categories", categories_path
          %li.divider
          %li= link_to "Logout", byebye_path

app/views/layouts/_live_chat.html.haml
<!-- Start of Async Drift Code -->
:javascript
  var __ac = {};
  __ac.uid = "e1c80645cdca267c88ead7f259fa2b75";
  __ac.server = "secure.chatrify.com";

  (function() {
    var ac = document.createElement('script'); 
    ac.type = 'text/javascript'; 
    ac.async = true;
    ac.src = 'https://cdn.chatrify.com/go.js';
    var s = document.getElementsByTagName('script')[0]; 
    s.parentNode.insertBefore(ac, s);
  })();

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name == :notice ? "success" : "alert"}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} ×

app/views/layouts/_navigation_links.html.haml
%li.divider
%li= link_to "Home",            root_path
%li.divider
%li= link_to "Technology",      technology_path
%li.divider
%li= link_to "Sports",          sports_path
%li.divider
%li= link_to "Entertainment",   entertainment_path
%li.divider
%li= link_to "World",           world_path
%li.divider

app/views/layouts/_page_level_ads.html.haml
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
(adsbygoogle = window.adsbygoogle || []).push({
google_ad_client: "ca-pub-8853705788192995",
enable_page_level_ads: true
});
</script>

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/[if IE 9 ] <html class="ie9" lang="en">
/ [if (gt IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "Early Morning Post", :name => "application-name"}/
    %meta{:content => "D9B2E54E17C77607F44057A2C737B103", :name => "msvalidate.01"}/
    - if content_for?(:head)
      = yield(:head)
    - else
      %meta{:content => "Early Morning Post", :name => "title"}
      %meta{:content => "News, Technology, Information, Google, Facebook, World", :name => "keywords"}
      %meta{:content => "Early Morning Post", :name => "title"}/
      %meta{:content => "Early Morning Post", :property => "og:title"}/
      %meta{:content => "website", :property => "og:type"}/
      %meta{:content => "www.earlymorningpost.com", :property => "og:url"}/
      %meta{:content => "Early Morning Post news about Technology, World, and everything else.", :property => "og:description"}/
      %meta{:content => "Early Morning Post news about Technology, World, and everything else.", :property => "description"}/
    %title= title
    / RSS FEED Link Tag
    = auto_discovery_link_tag(:rss, "http://www.earlymorningpost.com")
    / Google Authorship and Publisher Markup
    %link{:href => "https://plus.google.com/+Earlymorningpost7/posts", :rel => "author"}/
    %link{:href => "https://plus.google.com/+Earlymorningpost7", :rel => "publisher"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Roboto:400,300,900,100", :rel => "stylesheet", :type => "text/css"}/
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
    %link{:href => "http://fonts.googleapis.com/css?family=Chivo:900", :rel => "stylesheet", :type => "text/css"}/

    %link{:href => "apple-touch-icon.png", :rel => "apple-touch-icon"}
    %link{:href => "apple-touch-icon.png", :rel => "apple-touch-icon", :sizes => "76x76"}
    %link{:href => "apple-touch-icon.png", :rel => "apple-touch-icon", :sizes => "120x120"}
    %link{:href => "apple-touch-icon.png", :rel => "apple-touch-icon", :sizes => "152x152"}

    <!-- Global site tag (gtag.js) - Google Analytics -->
    %script{ async: true, src: "https://www.googletagmanager.com/gtag/js?id=UA-49061019-1" }
    %script
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-49061019-1');

    = render partial: "layouts/page_level_ads"
    = javascript_include_tag 'https://npmcdn.com/masonry-layout@4.0/dist/masonry.pkgd.js'
    = javascript_include_tag 'https://npmcdn.com/imagesloaded@4.1/imagesloaded.pkgd.js'

    = favicon_link_tag    'favicon.ico'
    = stylesheet_link_tag "application"
    = csrf_meta_tags
  %body{class: "#{@home_page ? 'homepage' : ''}"}
    = render 'shared/facebook_script'
    = render 'layouts/header'
    .row
      .large-12.large-centered.columns
        = render 'layouts/flash_messages'
    .row.custom-width
      .small-10.large-centered.columns
      = yield

    = render 'layouts/footer'
    = javascript_include_tag "application"